# Generated by Django 5.1.3 on 2024-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=33)),
            ],
        ),
    ]
