# Generated by Django 5.1.3 on 2024-11-05 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Za krótkie'), django.core.validators.MaxLengthValidator(15, message='Za długie')]),
        ),
    ]
