# Generated by Django 5.1.3 on 2024-11-05 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(5, message='Za krótkie')]),
        ),
    ]
